# Generated by Django 2.0.7 on 2018-07-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
